### ISSUE TITLE
React component state added infinite number of times

### ISSUE THREAD

**Issue by danstiner** [JoshuaKGoldberg/TypeStat#292]
Before:
```
export default class Notification extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      interval: this.createCountdown(props.start),
    }
  }
}
```

After:
```
export default class Notification extends React.Component<NotificationProps> {
state: { interval: NodeJS.Timer; };
state: { interval: NodeJS.Timer; };
state: { interval: NodeJS.Timer; };
state: { interval: NodeJS.Timer; };
state: { interval: NodeJS.Timer; };
state: { interval: NodeJS.Timer; };
state: { interval: NodeJS.Timer; };
...

  constructor(props) {
    super(props)

    this.state = {
      interval: this.createCountdown(props.start),
    }
  }
}
```

**Comment by ricardoafsilva** [comment]
I'm facing this problem too.

**Comment by JoshuaKGoldberg** [comment]
Ok! I took another look and believe this has since been resolved. @danstiner, since I'm sure you've been waiting to convert until this was resolved 😜, if you do still experience this issue please post here! I'll probably ask for your full `typestat.json`.

@ricardoafsilva, thanks for posting as well - if you're still trying TypeStat and experiencing this, please file a new issue. I'll probably ask for more details on the project contents, such as `ResultsContainer.tsx`.
